# Generated by Django 5.1.7 on 2025-03-16 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionSiteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(blank=True)),
                ('correlation_words', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_list', models.TextField(default='[]')),
                ('main_group', models.CharField(blank=True, max_length=15, null=True)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NewsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('source', models.CharField(max_length=255)),
                ('file_location', models.TextField(blank=True, null=True)),
                ('doi_id', models.CharField(blank=True, max_length=255, null=True)),
                ('affiliation', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordRecordSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_searcher.keywordrecord')),
                ('mail_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_searcher.mailgroup')),
            ],
        ),
        migrations.CreateModel(
            name='CorrelationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_searcher.keywordrecord')),
                ('news_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_searcher.newsrecord')),
            ],
        ),
    ]
