# Generated by Django 5.1.7 on 2025-03-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_searcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_group_name', models.CharField(max_length=255, null=True)),
                ('news_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news_searcher.newsrecord')),
            ],
        ),
    ]
